# ----------------------------------------------------------
# ------ Minecraft FTB SERVER | Docker Implementation ------
# ----------------------------------------------------------
version: '3.7'
services:

  ftb-server:
    container_name: ftb-server-mod-${MOD_ID}
    build:
      context: images/debian_FTB_server
      args:
        - MOD_ID
    image: ftb-server-mod-${MOD_ID}:1.0
    volumes:
      - ftb-mod:/var/FTB
    hostname: ftb-server-mod-${MOD_ID}
    ports:
      - "25565:25565/tcp"
    tty: true
    command: /bin/bash -c "cd /var/FTB && ./start.sh"

volumes:
  ftb-mod:
    driver: local