# ----------------------------------------------------------
# ------ Minecraft FTB SERVER | Docker Implementation ------
# ----------------------------------------------------------
version: '3'
services:


  ftb-server:
    container_name: ftb-server
    build: images/debian_FTB_server
    image: ftb-server:1.0
    volumes:
      - ftb:/var/FTB
    hostname: ftb-server
    ports:
      - "25565:25565"
    networks:
      ftb-net:
        ipv4_address: 100.0.0.2
    tty: true


volumes:
  ftb:
    driver: local


networks:
  ftb-net:
    driver: bridge
    ipam:
     config:
       - subnet: 100.0.0.0/16
         gateway: 100.0.0.1