# ----------------------------------------------------------
# ------ Minecraft FTB SERVER | Docker Implementation ------
# ----------------------------------------------------------
version: '3.7'
services:


  ftb-server:
    container_name: ftb-server
    build: images/debian_FTB_server
    image: ftb-server:1.0
    hostname: ftb-server
    ports:
      - "25565:25565"
      - "19132:19132"
    networks:
      ftb-net:
        ipv4_address: 100.0.0.2
    tty: true
    command: /bin/bash -c "cd /var/FTB && ./start.sh"


volumes:
  ftb:
    driver: local


networks:
  ftb-net:
    driver: bridge
    ipam:
     config:
       - subnet: 100.0.0.0/16
         gateway: 100.0.0.1